# Generated by Django 2.2 on 2019-04-09 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=60)),
                ('alive', models.BooleanField(default=True)),
                ('martial_stat', models.IntegerField(default=0)),
                ('intrigue_stat', models.IntegerField(default=0)),
                ('control_stat', models.IntegerField(default=0)),
                ('finance_stat', models.IntegerField(default=0)),
                ('charisma_stat', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['alive', 'player_id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.BooleanField(default=True)),
                ('turn', models.IntegerField(verbose_name='Turn Number')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Game')),
            ],
            options={
                'ordering': ['game_id', '-turn'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regency_app.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_1_type', models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_2_type', models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_3_type', models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_4_type', models.CharField(blank=True, choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_5_type', models.CharField(blank=True, choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Character')),
                ('command_1_player_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_1', to='regency_app.Player')),
                ('command_1_region_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_1', to='regency_app.Region')),
                ('command_1_region_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_1', to='regency_app.Region')),
                ('command_2_player_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_2', to='regency_app.Player')),
                ('command_2_region_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_2', to='regency_app.Region')),
                ('command_2_region_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_2', to='regency_app.Region')),
                ('command_3_player_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_3', to='regency_app.Player')),
                ('command_3_region_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_3', to='regency_app.Region')),
                ('command_3_region_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_3', to='regency_app.Region')),
                ('command_4_player_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_4', to='regency_app.Player')),
                ('command_4_region_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_4', to='regency_app.Region')),
                ('command_4_region_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_4', to='regency_app.Region')),
                ('command_5_player_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_5', to='regency_app.Player')),
                ('command_5_region_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_5', to='regency_app.Region')),
                ('command_5_region_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_5', to='regency_app.Region')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Game')),
                ('turn_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Turn')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regency_app.Player'),
        ),
    ]
