# Generated by Django 2.2 on 2019-04-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regency_app', '0002_auto_20190409_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_1_type', models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_2_type', models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_3_type', models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_4_type', models.CharField(blank=True, choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('command_5_type', models.CharField(blank=True, choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Character')),
                ('command_1_player_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_1', to='regency_app.Player')),
                ('command_1_region_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_1', to='regency_app.Region')),
                ('command_1_region_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_1', to='regency_app.Region')),
                ('command_2_player_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_2', to='regency_app.Player')),
                ('command_2_region_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_2', to='regency_app.Region')),
                ('command_2_region_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_2', to='regency_app.Region')),
                ('command_3_player_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_3', to='regency_app.Player')),
                ('command_3_region_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_3', to='regency_app.Region')),
                ('command_3_region_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_3', to='regency_app.Region')),
                ('command_4_player_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_4', to='regency_app.Player')),
                ('command_4_region_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_4', to='regency_app.Region')),
                ('command_4_region_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_4', to='regency_app.Region')),
                ('command_5_player_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_5', to='regency_app.Player')),
                ('command_5_region_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_5', to='regency_app.Region')),
                ('command_5_region_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_5', to='regency_app.Region')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Turn')),
            ],
        ),
        migrations.DeleteModel(
            name='Commands',
        ),
    ]
