# Generated by Django 2.2 on 2019-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regency_app', '0003_auto_20190409_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('ZUL', 'Zulia'), ('ULE', 'Ule'), ('DAX', 'Daxia'), ('WI', 'Western Isles'), ('CHE', 'Cherobek'), ('SAY', 'Sayenne')], max_length=30),
        ),
    ]
