# Generated by Django 2.2 on 2019-04-09 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regency_app', '0004_auto_20190409_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma_stat',
            field=models.IntegerField(default=0, verbose_name='Charisma'),
        ),
        migrations.AlterField(
            model_name='character',
            name='control_stat',
            field=models.IntegerField(default=0, verbose_name='Control'),
        ),
        migrations.AlterField(
            model_name='character',
            name='finance_stat',
            field=models.IntegerField(default=0, verbose_name='Finance'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intrigue_stat',
            field=models.IntegerField(default=0, verbose_name='Intrigue'),
        ),
        migrations.AlterField(
            model_name='character',
            name='martial_stat',
            field=models.IntegerField(default=0, verbose_name='Martial'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='character',
            field=models.ForeignKey(limit_choices_to={'alive': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='regency_app.Character'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_1_player_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_1', to='regency_app.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_1_region_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_1', to='regency_app.Region', verbose_name='From Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_1_region_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_1', to='regency_app.Region', verbose_name='To Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_1_type',
            field=models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_2_player_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_2', to='regency_app.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_2_region_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_2', to='regency_app.Region', verbose_name='From Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_2_region_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_2', to='regency_app.Region', verbose_name='To Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_2_type',
            field=models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True, verbose_name='Command 2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_3_player_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_3', to='regency_app.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_3_region_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_3', to='regency_app.Region', verbose_name='From Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_3_region_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_3', to='regency_app.Region', verbose_name='To Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_3_type',
            field=models.CharField(choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True, verbose_name='Command 3'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_4_player_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_4', to='regency_app.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_4_region_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_4', to='regency_app.Region', verbose_name='From Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_4_region_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_4', to='regency_app.Region', verbose_name='To Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_4_type',
            field=models.CharField(blank=True, choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True, verbose_name='Command 4'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_5_player_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_target_5', to='regency_app.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_5_region_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_source_5', to='regency_app.Region', verbose_name='From Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_5_region_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_target_5', to='regency_app.Region', verbose_name='To Region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='command_5_type',
            field=models.CharField(blank=True, choices=[('Tax', 'Tax'), ('Trade', 'Trade'), ('Income', 'Income'), ('Move', 'Move'), ('Train', 'Train'), ('Disband', 'Disband'), ('Scheme', 'Scheme'), ('Bribe', 'Bribe'), ('Assas', 'Assassinate'), ('Theft', 'Theft'), ('Skill', 'Advance Skill'), ('Hide', 'Hide'), ('Contest', 'Contest'), ('Spawn', 'Insight Rebellion'), ('Petition', 'Petition the Gods')], max_length=10, null=True, verbose_name='Command 5'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'game')},
        ),
    ]
